### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by crshrprt** [lachesis17/Delay-ja-vu#1]
Thank you for this interesting plugin.

I can't find if the source is released under a license. Is there a license?

**Comment by lachesis17** [comment]
Thanks. 

It seems a bit odd for a user with 0 repositories to be asking about licenses out of the blue and your history suggests you do this a lot (with the same copy/paste message).

The code is public to share knowledge and for potential employers. It is not shared for redistribution, monetary or otherwise.

If that was your intention, then it's all rights reserved, source available, not open source.

_"By default, without an explicit license, your work is protected by copyright laws, and others cannot legally reproduce, distribute, modify, or otherwise use your work without your permission. This is the default state when you create a new repository without adding a license."_

**Comment by crshrprt** [comment]
@lachesis17 thank you for your answer.

If you look at my history on Github a bit deeper you can see my intention is to contribute, report bugs or help in general, to the best of my little knowledge (I'm not a developer), to open source projects. 
Another thing I'm trying to do is to spread the knowledge about very new or little known open source projects, mainly on Linux and exclusively 100% FOSS.

Regarding my "asking about licenses out of the blue", is because many developers publish their code with the intention of it being open source, and sometimes the forget to add a LICENSE or stating it in other forms  (again, if you look a bit deeper in my history).

Thank you again for clarifying, good luck with your project.

**Comment by lachesis17** [comment]
@crshrprt Thanks for clarifying, it's a bit of a relief.

I wasn't sure how to respond and asked other JUCE developers for advice, which sparked a long discussion about licensing with polarizing opinions. It was difficult to gauge your intent and given the niche and propietary nature of audio plugins and advice I received, I acted defensively.

I'm just learning and plugins are personal passion projects, as they are for many others and I want to keep the code public for anyone who may find it useful.

Best of luck.
